
  # docker-compose.yaml
version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'skinseoulution'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql

  server:
    build: ./server
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/skinseoulution?allowPublicKeyRetrieval=true&useSSL=false'
      SPRING_DATASOURCE_USERNAME: 'jan'
      SPRING_DATASOURCE_PASSWORD: 'janjan'

  client:
    build: ./client
    ports:
      - '4200:4200'

volumes:
  db_data:




